### ISSUE TITLE
[FEATURE]Change static-nodes.json for general node.

### ISSUE THREAD

**Issue by hagishun** [BoostryJP/ibet-Network#53] opened 2021-07-05 19:40 UTC
**Is your feature request related to a problem? Please describe.**

- Regular update of ibet network will be done in July 2021.
- We will change static-nodes.json for general nodes.

**Describe the solution you'd like**

- As above.

**Comment by YoshihitoAso** [comment] 2021-07-05 22:30
Is this a duplicate of # 52?

**Closed** 2021-07-07 03:07 UTC
Labels: duplicate
